version: '3.8'
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - ALLOWED_ORIGINS=http://localhost:3000
      - DB_PATH=/app/math_tutor_db
      - DOCS_PATH=/app/math_docs
    volumes:
      - ./math_docs:/app/math_docs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3 