[build]
builder = "nixpacks"
buildCommand = """
python -m venv venv
source venv/bin/activate
pip install --upgrade pip
pip install -r backend/requirements.txt
"""

[deploy]
startCommand = "cd backend && uvicorn api:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
PYTHON_VERSION = "3.10"

[[services]]
name = "pythagore-backend"
internal_port = 8000
protocol = "http"

[[services.ports]]
handlers = ["http"]
port = 80