[build]
builder = "nixpacks"
buildCommand = "pip install -r backend/requirements.txt && pip install -r backend/requirements-ml.txt"

[deploy]
startCommand = "uvicorn backend.api:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 10

[env]
PYTHON_VERSION = "3.10"
NIXPACKS_PYTHON_VERSION = "3.10"
PYTHONPATH = "/app"