[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "uvicorn backend.api:app --host 0.0.0.0 --port 8000"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicy = "on-failure"

[env]
PYTHON_VERSION = "3.10"
NIXPACKS_PYTHON_VERSION = "3.10"
PYTHONPATH = "/app"